### ISSUE TITLE
tolong sertakan database

### ISSUE THREAD

**Issue by Mufrida** [muhammaddicky/SIAKAD-PT#3]
boleh minta databasenya ?

**Comment by mryoga** [comment]
udah dapat lum gan db nya

**Comment by teguhwin8** [comment]
Gimana cara mendownload databasenya?

**Comment by mrsetia1** [comment]
dijual ga???

**Comment by nonohry** [comment]
kalau mau ada databasenya download dari sini https://github.com/muhammaddicky/SIAKAD-PT/releases

**Comment by teguhwin8** [comment]
Ga gan, cuma buat belajar aja, buat pribadi

Pada tanggal Jum, 18 Okt 2019 pukul 17.14 Muhammad Rizal Setiawan <
notifications@github.com> menulis:
